# Site
title: Ernestas Narmontas
description: Personal Blog
baseurl: ""
url: "https://ernestas.me"

# Author
author:
  name: Ernestas Narmontas
  email: ernestasn@pm.me
  url: https://ernestas.me

# Settings
permalink: /:year/:month/:day/:title
markdown: kramdown
paginate: 5
remote_theme: enarmontas/tale
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll_github_sample
  - jekyll-twitter-plugin
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-59118080-2

exclude:
  - README.md
  - LICENSE.txt
  - Gemfile.lock
  - Gemfile

feed:
  tags:
    only:
      - devto

staticman_url: https://ernestas-me-staticman.herokuapp.com/v3/entry/enarmontas/enarmontas.github.io/master/comments
reCaptcha:
  siteKey: 6LfbfUsaAAAAAGjuUw-KsmEs2JKV8t3KlTQ5LyII
  secret: KWzol/tQBI3TmYjWmQk8K5QsScmy3M2bWe5vNq35FPr0Zr1y03ZJeh1SOQZn8vvLFK1QuP+03ZAOhDOjh+OUnnFhuMleIwI9KflVudtOfwhkZUwkX82GEOtg+KDQPAY8CNxo5Xk2qONa8wt9iCM71Cx3dgcGsQiVILqNvpwKAXpAFNJvJLwKWOJkjd0GGl7whzlWM8MuNiddYPnX59QmnX9Q3v3C4KGZqWic62q3AoCYy4a2up9GkbQCL7bZLvsCfPvR+48sYn2e6w+T7livjBTnKpehkDAGJyqXrzbD68WLbCmPvW++Y1OptvXAj0ggmutr6W0+Im9tQ4FA83VQIlvRw9ch57NPARU+xozoHY28pYXszo0f7/Wz0SC7ILnK+PZlsMJfu7gBYkL8Y14RQ0HDTyZkY/MWdKYCM4TAhTvDvvE23OhnEn4ENkCw7izjOnQ31mJbUvYC36rdwloZrxpwNKMQBTyb0m0CllPW/Fv+mBFZQg1uBTVmknDLvROjDO/uijrJikYwtlkvNyMzJaLVg7Hc0827qr1wDNcn+zCjBAhXkWNAGLJJKgnYH+epR50yHg5wlBxMV4UXBMWoi6nDvyfQKW8O5oc6luxgd1UAC1hKFWEPoN5bokl4P/D7r5rdMWQdIyDHoc0wRN26E+oWBkC7Th29gSK0fCeYCJc=
