# Site
title: Ernestas Narmontas
description: Personal Blog
baseurl: ""
url: "https://ernestas.me"

# Author
author:
  name: Ernestas Narmontas
  email: ernestasn@pm.me
  url: https://ernestas.me

# Settings
permalink: /:year/:month/:day/:title
markdown: kramdown
paginate: 5
remote_theme: ernnst/tale
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
